[project]
name = "tools4ds"
version = "0.1.0"
description = "Utilities from IBM Tools for Data Science course"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.ruff]
line-length = 100

[tool.mypy]
python_version = "3.10"
strict = true